# This file has been generated by node2nix 1.6.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "vscode-css-languageservice-3.0.11" = {
      name = "vscode-css-languageservice";
      packageName = "vscode-css-languageservice";
      version = "3.0.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-css-languageservice/-/vscode-css-languageservice-3.0.11.tgz";
        sha512 = "XweDpjcD+VMguJMcr5V1OHE3GclVWJ7DpojpxrlsGCJlUumY/Xrv4VcMta6z7wUBwsmOeyogT5Hf/L2SzBg6Jw==";
      };
    };
    "vscode-jsonrpc-4.0.0" = {
      name = "vscode-jsonrpc";
      packageName = "vscode-jsonrpc";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-jsonrpc/-/vscode-jsonrpc-4.0.0.tgz";
        sha512 = "perEnXQdQOJMTDFNv+UF3h1Y0z4iSiaN9jIlb0OqIYgosPCZGYh/MCUlkFtV2668PL69lRDO32hmvL2yiidUYg==";
      };
    };
    "vscode-languageserver-4.4.2" = {
      name = "vscode-languageserver";
      packageName = "vscode-languageserver";
      version = "4.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver/-/vscode-languageserver-4.4.2.tgz";
        sha512 = "61y8Raevi9EigDgg9NelvT9cUAohiEbUl1LOwQQgOCAaNX62yKny/ddi0uC+FUTm4CzsjhBu+06R+vYgfCYReA==";
      };
    };
    "vscode-languageserver-protocol-3.13.0" = {
      name = "vscode-languageserver-protocol";
      packageName = "vscode-languageserver-protocol";
      version = "3.13.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver-protocol/-/vscode-languageserver-protocol-3.13.0.tgz";
        sha512 = "2ZGKwI+P2ovQll2PGAp+2UfJH+FK9eait86VBUdkPd9HRlm8e58aYT9pV/NYanHOcp3pL6x2yTLVCFMcTer0mg==";
      };
    };
    "vscode-languageserver-protocol-foldingprovider-2.0.1" = {
      name = "vscode-languageserver-protocol-foldingprovider";
      packageName = "vscode-languageserver-protocol-foldingprovider";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver-protocol-foldingprovider/-/vscode-languageserver-protocol-foldingprovider-2.0.1.tgz";
        sha512 = "N8bOS8i0xuQMn/y0bijyefDbOsMl6hiH6LDREYWavTLTM5jbj44EiQfStsbmAv/0eaFKkL/jf5hW7nWwBy2HBw==";
      };
    };
    "vscode-languageserver-types-3.13.0" = {
      name = "vscode-languageserver-types";
      packageName = "vscode-languageserver-types";
      version = "3.13.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver-types/-/vscode-languageserver-types-3.13.0.tgz";
        sha512 = "BnJIxS+5+8UWiNKCP7W3g9FlE7fErFw0ofP5BXJe7c2tl0VeWh+nNHFbwAS2vmVC4a5kYxHBjRy0UeOtziemVA==";
      };
    };
    "vscode-nls-4.0.0" = {
      name = "vscode-nls";
      packageName = "vscode-nls";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-nls/-/vscode-nls-4.0.0.tgz";
        sha512 = "qCfdzcH+0LgQnBpZA53bA32kzp9rpq/f66Som577ObeuDlFIrtbEJ+A/+CCxjIh4G8dpJYNCKIsxpRAHIfsbNw==";
      };
    };
    "vscode-uri-1.0.6" = {
      name = "vscode-uri";
      packageName = "vscode-uri";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-uri/-/vscode-uri-1.0.6.tgz";
        sha512 = "sLI2L0uGov3wKVb9EB+vIQBl9tVP90nqRvxSoJ35vI3NjxE8jfsE5DSOhWgSunHSZmKS4OCi2jrtfxK7uyp2ww==";
      };
    };
  };
in
{
  vscode-css-languageserver-bin = nodeEnv.buildNodePackage {
    name = "vscode-css-languageserver-bin";
    packageName = "vscode-css-languageserver-bin";
    version = "1.4.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/vscode-css-languageserver-bin/-/vscode-css-languageserver-bin-1.4.0.tgz";
      sha512 = "KWrF5f4RYYe8RBDfqb1c0Sdf9xPS2Ly/Z/T18H+uUOMw2QyzIrkxv4bMKy5GFfPm4479k6Ln4ji4UHqSmhGf3g==";
    };
    dependencies = [
      sources."vscode-css-languageservice-3.0.11"
      sources."vscode-jsonrpc-4.0.0"
      sources."vscode-languageserver-4.4.2"
      sources."vscode-languageserver-protocol-3.13.0"
      sources."vscode-languageserver-protocol-foldingprovider-2.0.1"
      sources."vscode-languageserver-types-3.13.0"
      sources."vscode-nls-4.0.0"
      sources."vscode-uri-1.0.6"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Binary version published on npm of vscode-css-languageserver extracted from VSCode tree";
      homepage = "https://github.com/vscode-langservers/vscode-css-languageserver-bin#readme";
      license = "MIT";
    };
    production = false;
    bypassCache = true;
  };
}